// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/Layout/aside/aside.vue')['default']
    AsideMenu: typeof import('./src/Layout/aside/asideMenu.vue')['default']
    Button: typeof import('vexip-ui')['Button']
    Home: typeof import('./src/views/home.vue')['default']
    Input: typeof import('vexip-ui')['Input']
    Layout: typeof import('vexip-ui')['Layout']
    Menu: typeof import('vexip-ui')['Menu']
    NumberInput: typeof import('vexip-ui')['NumberInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('vexip-ui')['Select']
    Space: typeof import('vexip-ui')['Space']
    Switch: typeof import('vexip-ui')['Switch']
    Test: typeof import('./src/views/test.vue')['default']
    ThemeSwitch: typeof import('./src/Layout/header/ThemeSwitch.vue')['default']
    Undefined: typeof import('./src/Layout/index.vue')['default']
  }
}
